language: java
cache:
  directories:
  - "$HOME/.m2"
  - docker_images
sudo: required
services:
- docker
notifications:
  email:
  - shubhamr837@gmail.com
  on_success: always
  on_failure: always
branches:
  only:
  - master
env:
  global:
    - secure: MAzcDRwI6EVDSFV1S/KP1FhvChRAG9bZK7/GI/fDSKTJDfpwexgXFCvyokE+QvedtP4pI31ao3CG+cI0Q7tuGeX+YndMe9uMsR6F5UtKYk0+3m+pP1g7p5KwwlvghccLja7KnWHK73y2L1ZyE5M0LBs/5IK4q9PJcgtOlbXzecie1uEyR6MXheHD762Ny0bRM9uLKFRGGlHOe4KOAWpIGwwS8rThpdfqtXF8QiFi0GVKy6ZdJeCClvG1+ApFg8sHQwNG9ckQjKKASIlf62SNl33n4XKj39nw4R6fdm1CYsXL7JoX/kBZ5B+MAV1Iei+aK6Lb34rj/G312LWD7gXrPvuZJLowLVi9WExhy4rt78ftUZoxBlzeyCd6p6R1uZDIATpDpbhUxtov158BRfSu6uYquFx0bKn0sN0jOeWHNxRE76GxqQO2jjaUtK7YrMBay39xVIw1WD1lIQ9klnW4x2sZfuJqjStQcyNQ2KONXeOWMoESdNQA0omFirzBR1m2JAK0iGMIHDi2QPeKZOQTqrCuklwUmUwf55cRD89km2ytDNGkUrUTCyR4yKLO2qL9jpP7g8Q5qsJ/NB1snFFiYoeIsU1tRNy4yB46h1dC3ZB6BUWs0OzO/xZg+JZRfIjuEe9OWb1bcPfadBmQTSPhGhTDJTuVmqdc7W2CyUNHUkQ=
    - secure: gWFN9dVY9e0Y0GCFP8Wb6LzoX2s2Tb/ch6yZRHkDnv0aLNWtX9Sy4kQcJUOAqJbFVMn1jWQ9IEOK3yvcsqIno8BMrePuHRiemw4jgyLN9wUNUVzugGU6EfqcEdOPdpfIcTyFHUownX1MC8I+PNp+fkxSWdyNuEPcrArB3+hUWSfM0TrB78dhMU+Q2+3AtjSbEbovT5tnBqJO7/Wkg/VF0mnaYBe2AGkqsxlz/A6P/wkAeeBvXIXrK3vm4oMHuk63lBelBEa+pwvSj98U+vm14/FQefHPy0uJI6bZUTvaCl2oMSyOlNLs9tY7g+eeZLAyhSAgTPXe2Tmm9lIl8rhEgIJqtKvc40fLRhjE7OXgSJYI5nJIotY1+EdWtjdwsetF1+OPkNZse4bXAOuwhayupIUa/LDMduqVIt9uVQOtlpB0y8ygXauElYEwpBlwy8RIg5UqELJmvov8JN8TKVVGpeATiY36EQUz36LW/UAeNBrOQvgkQEdUd0hCOf4g3LLhrT0A0pB8SIRlQC88krlFqVhHPPkWfDYy58jvRAUlWKkaY/sJ+dkQMgein6+h+aGg0hTZ6Qpr5gZdsy+OVea51gmpkoVbe38i37c3aIo2P4Kyj3Qc7eezgr1dvGnitIy54owAlj4Vq7UQz7JeqrEAtVmxooF2e8xiXQrUY8P6AxE=
before_install:
  - openssl aes-256-cbc -K $encrypted_7cfcfc98630c_key -iv $encrypted_7cfcfc98630c_iv
    -in Dockerfile.enc -out Dockerfile -d
- docker load -i docker_images/images.tar || true
- export AWS_DEFAULT_REGION=us-east-2
script:
  - "./mvnw package"
  - docker build --build-arg AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID --build-arg AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    -t shubhamr837 .
- docker tag shubhamr837:latest pdf-server
- docker push shubhamr837/pdf:pdf-server
before_cache:
  - docker save -o docker_images/images.tar $(docker images -a -q)
