language: java
cache:
  directories:
  - "$HOME/.m2"
  - "docker_images"
sudo: required
services:
- docker
notifications:
  email:
  - shubhamr837@gmail.com
  on_success: always
  on_failure: always
branches:
  only:
  - master
before_install:
- docker load -i docker_images/images.tar || true
script:
- ./mvnw package

- docker build -t shubhamr837 .
- docker tag shubhamr837:latest shubhamr837/pdf:pdf-server
- docker push shubhamr837/pdf:pdf-server

before_cache:
  - docker save -o docker_images/images.tar $(docker images -a -q)
