apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pdftoword
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pdftoword
    spec:
      containers:
        - name: pdftoword
          image: gcr.io/crested-ratio-257703/pdf-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
